#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "{BASH_SOURCE[0]"}) && pwd)
rm -rf $HOME/.wezterm.lua
ln -s $DOTFILES/wezterm/.wezterm.lua $HOME/.wezterm.lua

rm -rf $HOME/.config/wezterm/keybindings.lua
ln -s $DOTFILES/wezterm/keybindings.lua $HOME/.config/wezterm/keybindings.lua

rm -rf $HOME/.config/wezterm/config-utility.lua
ln -s $DOTFILES/wezterm/config-utility.lua $HOME/.config/wezterm/config-utility.lua

rm -rf $HOME/.config/wezterm/status-bar.lua
ln -s $DOTFILES/wezterm/status-bar.lua $HOME/.config/wezterm/status-bar.lua

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty/ $HOME/.config/kitty

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin
rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor
